services:
  server:
    image: api/server
    container_name: api-server
    hostname: api-server
    volumes:
      - "./server:/app"
    ports:
      - "${SERVER_HTTP_PORT:-80}:80"
      - "${SERVER_HTTPS_PORT:-443}:443"
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: unless-stopped
    container_name: api-db
    environment:
      MYSQL_ROOT_PASSWORD: 123123
    ports:
      - "3306:3306"

  client:
    image: api/client
    container_name: api-client
    hostname: api-client
    environment:
      SERVER_API_URL: "https://api-server/api/"
      XDEBUG_CONFIG: 'idekey=PHPSTORM client_host=host.docker.internal client_port=9003 mode=debug,develop'
      PHP_IDE_CONFIG: 'serverName=client'
    volumes:
      - "./client:/app"
    command: tail -f
